[build]
  cmd = "go build -o ./tmp/main ./main"
  bin = "./tmp/main"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "node_modules"]
  delay = 1000
  stop_on_error = true

